version: '3.6'

services:
  springboot-redis:
    image: 192.168.13.129:23456/springboot-redis
    build: .
    ports:
      - 8080:8080
    environment:
      - spring.profiles.active=docker
      JAVA_OPTS: "-javaagent:/pinpoint-agent/pinpoint-bootstrap-1.8.4.jar -Dpinpoint.agentId=springboot-redis-in-docker -Dpinpoint.applicationName=springboot-redis"
    links:
      - redis
  redis:
    image: 192.168.13.129:23456/redis:5.0-alpine
    container_name: redis

  pinpoint-agent:
    container_name: "pinpoint-agent"
    image: "192.168.13.129:12345/pinpoint-agent:1.8.4"
    restart: unless-stopped
    networks:
      - pinpoint
    volumes:
      - data-volume:/pinpoint-agent
    environment:
      - COLLECTOR_IP=${COLLECTOR_IP}
      - COLLECTOR_TCP_PORT=${COLLECTOR_TCP_PORT}
      - COLLECTOR_STAT_PORT=${COLLECTOR_STAT_PORT}
      - COLLECTOR_SPAN_PORT=${COLLECTOR_SPAN_PORT}
      - PROFILER_SAMPLING_RATE=${PROFILER_SAMPLING_RATE}
      - DEBUG_LEVEL=${AGENT_DEBUG_LEVEL}
